def raise_exception():
    value = "Hello, World!"
    result = value + 42 
    return result

raise_exception()